# spring.application.name=chap02-handler-method-lecture-source
# spring.application.name=chap01-request-mapping-lecture-source
spring:
  application:
    name: chap02-handler-method-lecture-source
server:
  port: 8001  # ?? ??? ?? ? ??