spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqrs
    username: swcamp
    password: swcamp
  output:
    ansi:
      enabled: always

image:
  image-dir: C:/upload/productimgs
  image-url: http://localhost:8080/productimgs/