# ?? ??? ?? ??
spring:
  servlet:
    multipart:
      # ?? ?? ??(???? ??? ?? ???? ????)
      location: /Users/junga/dev/playdata/uploadFiles
      # ?? ??? ?? ??
      max-file-size : 10MB
      # ?? ?? ?? ??
      max-request-size: 10MB