# ?? ??? ?? ??
spring:
  servlet:
    multipart:
      # ?? ?? ??(???? ??? ?? ???? ?? ??
      location: /Users/parkchangjun/Documents/Dev/uploadFiles
      # ?? ??? ?? ??
      max-file-size: 10MB
      # ?? ?? ?? ??
      max-request-size: 10MB