#spring.application.name=chap06-file-upload-lecture-source
# ?? ??? ?? ??
spring:
  servlet:
    multipart:
      # ?? ?? ??(???? ??? ?? ???? ?? ??)
      location: C:\dev\uploadFiles
      # ?? ??? ?? ??
      max-file-size: 10MB
      # ?? ?? ?? ?? ??
      max-request-size: 10MB

